issuer/create_certificates.py
issuer/helpers.py
issuer/wallet.py
tests/test_create_certificates.py

Fixes to make temp addresses work. This is critical for issuing batches of certificates.

make temp addresses and batches work

---

README.md
docs/docker.md
docs/index.md
docs/precommit.md
mkdocs.yml
pre-commit.sh

The docker / quick start steps were duplicated between README.md and docs/docker.md. Keeping these in sync is error prone. See #26 in cert-viewer
Added comment markers around the relevant parts of README.md, added a pre-commit hook to slurp in those instructions to copy to docs/docker.md.
Also added unit tests to pre-commit hook.

Remove duplicate docker instructions, add pre-commit hooks

---

cert_issuer/__init__.py
cert_issuer/issue_certificates.py
cert_issuer/issuer.py

Avoid duplicate lookups by allowing callers to pass prepared inputs

allow prepared inputs

---

cert_issuer/__init__.py
cert_issuer/issue_certificates.py
cert_issuer/issuer.py
cert_issuer/transaction_handler.py
cert_issuer/tx_utils.py

Transaction fees calculated up front are estimates until we know exact number of inputs, and whether change is required. Fix naming and and also use precise counts as soon as we know them.

Kh cleanup names

---

cert_issuer/ethereum/connectors.py

When calling get_providers_for_chain, it should have an argument "local_node" tho it is not used.

add: missing argument for get_providers_for_chain

---

setup.py

Should fix #83
Append was adding the list like: `[1, 2, 3, [4, 5, 6]]`, extend adds them like `[1, 2, 3, 4, 5, 6]`
Pip imports were breaking in 10+, changing that out for subprocess as recommended here: https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program

Fixing dependency loading and moving from unsupported pip command

---

README.md
cert_issuer/config.py
cert_issuer/ethereum/__init__.py
cert_issuer/issue_certificates.py
conf_ethtest.ini
conf_template.ini

Removing testnet from the Ethereum options, as part of Issue https://github.com/blockchain-certificates/cert-issuer/issues/72
`ethereum_ropsten` should be used instead.

Removed ethereum testnet, should use ropsten instead

---

cert_issuer/config.py

Logging is happening twice, due to `configure_logger()` at the beginning of the method and this one at the end.

Removing 2nd instance of logger

---

README.md

Minor bug fix to build instructions for `docker build` with build-args.

fix minor bug in documentation

---

app.py
cert_issuer/certificate_handlers.py
tests/test_certificate_handler.py
tests/test_signer.py
wsgi.ini
wsgi.py

Fix for [issue](https://github.com/blockchain-certificates/cert-issuer/issues/120) 120:

Merkle proof update for web batch

---

cert_issuer/certificate_handlers.py
tests/test_certificate_handler.py

I run the demo as quick start described, however get an error:
```
ab987a087865:/etc/cert-issuer# cert-issuer -c /etc/cert-issuer/conf.ini
WARNING - Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO - This run will try to issue on the bitcoin_regtest chain
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Processing 1 certificates
INFO - Processing 1 certificates under work path=/etc/cert-issuer/work
INFO - Total cost will be 133500 satoshis
INFO - Starting finalizable signer
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is …
```

fix bad iteration in finish_batch certificate_handlers.py

---

README.md

This PR clarifies how to run cert-issuer to issue certs.  This addresses issue https://github.com/blockchain-certificates/cert-issuer/issues/129

clarify readme instructions for running cert-issuer

---

Dockerfile.web
README.md
docs/web_resources.md
start-cert-issuer.sh

This PR creates a separate page for describing setting up and testing the cert-issuer web and creates a link from the main README.  I also added a file `start-cert-issuer.sh` which can be used to streamline testing by overriding the docker entrypoint described in the docs.

Create a separate page for describing web services

---

requirements.txt

Pycoin  v0.90 came almost 2 years after v0.80, and this latest version introduces a lot of non-backwards compatible changes:
- `b2h`, `h2b` `h2b_rev` and `b2h_rev` were moved from `serialize` to `encoding.hexbytes`
- `Spendable` was moved from `tx.Spendable` to `coins.bitcoin.Tx`
...and many more changes.
This version lock prevents `cert-issuer` from breaking.

Lock pycoin version.

---

README.md

Changing to the new location of Merkleproof-2017 from https://w3c-dvcg.github.io/lds-merkleproof2017/ to https://w3c-ccg.github.io/lds-merkleproof2017/

fix: update new web location of Merkleproof-2017

---

Dockerfile

this will also support more architectures (like Apple M1 ones)
this will fix https://github.com/blockchain-certificates/cert-issuer/issues/221

Move to a more updated image for bitcoind

---

README.md

Hi, Blockcerts maintainers
I found a dead link, so I corrected it.
Could you check this?

Correct the dead link of Merkle Proof Signature Suite 2019

---

README.md
cert_issuer/blockchain_handlers/bitcoin/__init__.py
cert_issuer/blockchain_handlers/ethereum/__init__.py
cert_issuer/blockchain_handlers/ethereum/connectors.py
cert_issuer/blockchain_handlers/ethereum/signer.py
cert_issuer/config.py
cert_issuer/helpers.py
cert_issuer/issue_certificates.py
cert_issuer/merkle_tree_generator.py
conf_ethtest.ini
docs/ethereum_configuration.md
requirements.txt

Hi maintainers,
This PR is to allow using Ethereum testnets, the Goerli and the Sepolia.
We have discussed this on [this forum page](https://community.blockcerts.org/t/ethereum-announced-the-testnet-ropsten-would-be-closed-in-q4-2022/3227).
Could you check this?
After set to use the related changed [cert-core](https://github.com/blockchain-certificates/cert-core/pull/4) and [lds-merkle-proof-2019-py](https://github.com/blockchain-certificates/lds-merkle-proof-2019-py/pull/4), I confirmed the following cases:
- Goeril
- it issues a VC and saves the transaction on Goerli ([Actual Transaction](https://goerli.etherscan.io/tx/0xfb593f186a274f58f861e5186150bc692ed533c7af50efb094f756ccb81c7023))
- it issues a VC and saves the transaction on Goerli with env:`GOERLI_RPC_URL` set …

Support Ethereum testnets, the Goerli and the Sepolia

---

cert_issuer/blockchain_handlers/ethereum/__init__.py
cert_issuer/blockchain_handlers/ethereum/connectors.py
cert_issuer/blockchain_handlers/ethereum/signer.py
cert_issuer/blockchain_handlers/ethereum/transaction_handlers.py
cert_issuer/blockchain_handlers/ethereum/tx_utils.py
cert_issuer/config.py
ethereum_requirements.txt
requirements.txt

Hi there, it's been about a year since the London hardfork (EIP-1559) changed how Ethereum gas fees are handled and it would be good for Blockcerts to use the updated transaction format. Two major reasons not to use the old transaction format anymore:
1) It's deprecated
2) It guarantees overpayment of gas fees. Miners will always receive the entire proposed gas fee, whereas with EIP-1559 txs, they will only receive the base fee plus the priority fee. For what it's worth, my gas fees have been about 75% less with this update.
[Here's a good primer on EIP-1559](https://medium.com/alchemy-api/the-developer-eip-1559-prep-kit-72dbe5c44545) if more background info is desired.
To enable EIP-1559-compliant transactions, I had to update some of the old web3-related libraries that were being used. …

Enable EIP-1559 ETH txs and update deprecated web3 methods/packages

---

.travis.yml

it seems we are in a detached state, probably due to such a command early on in the CI process: https://app.travis-ci.com/github/blockchain-certificates/cert-issuer/builds/269278175#L173.
So we force back into master

chore(CI): re-enable semantic release publish

---

cert_issuer/blockchain_handlers/ethereum/__init__.py
cert_issuer/blockchain_handlers/ethereum/connectors.py
cert_issuer/config.py

Currently cert issuer supports setting a fixed gas price to issue credentials into the Ethereum blockchain. When issuing credentials via an automated process, using the cert issuer APIs, a fixed value would need constant intervention or it needs to have a high value. Neither of which is scalable or cost efficient.
To handle this case, I have introduced a `gas_dynamic_price` config which when set to `True`, will fetch the current gas price from Etherscan.
Issue: https://github.com/blockchain-certificates/cert-issuer/issues/285

Fetching current gas price from Etherscan

---

app.py
cert_issuer/blockchain_handlers/ethereum/__init__.py
cert_issuer/blockchain_handlers/ethereum/transaction_handlers.py
cert_issuer/normalization_handler.py

Currently the `/cert_issuer/api/v1.0/issue` API only supports issuing credentials in the Bitcoin Blockchain.
This PR adds the ability to issue credentials into the Ethereum Blockchain using the same API. The API contract has been updated as follows
- `POST /cert_issuer/api/v1.0/issue` - issues to the Bitcoin Blockchain, which is the existing and default behaviour.
- `POST /cert_issuer/api/v1.0/issue/bitcoin` - issues to the Bitcoin Blockchain, which is also supported for consistency.
- `POST /cert_issuer/api/v1.0/issue/ethereum` - issues to the Ethereum Blockchain.

Support for issuing Credentials to the Ethereum Blockchain via API
